# TODO: Change this to be parsed from the event, not here
count_at_start = 2

[[stack_matcher]]
classification = "increment"
[[stack_matcher.top]]
type = "symbolicated"
module = "d3d11.dll"
symbol_name = "TComObject<NOutermost::CDevice>::AddRef"

[[stack_matcher]]
classification = "decrement"
[[stack_matcher.top]]
type = "symbolicated"
module = "d3d11.dll"
symbol_name = "TComObject<NOutermost::CDevice>::Release"

[[stack_matcher]]
classification = "destructor"
[[stack_matcher.top]]
type = "symbolicated"
module = "d3d11.dll"
symbol_name = "TComObject<NOutermost::CDevice>::~TComObject<NOutermost::CDevice>"
